# Generated by Django 4.2.1 on 2024-04-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Dog.category'),
        ),
    ]
