# Generated by Django 4.2.1 on 2024-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='dog',
            name='slag',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['-time_create'], name='Dog_dog_time_cr_375f1a_idx'),
        ),
    ]
