# Generated by Django 4.2.1 on 2024-04-30 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Dog', '0002_alter_dog_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Dog.category'),
        ),
    ]
