# Generated by Django 4.2.1 on 2024-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog', '0002_alter_dog_options_dog_slag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='slag',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
