# Generated by Django 4.2.1 on 2024-04-29 09:02

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Dog', '0004_rename_slag_dog_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dog',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
