# Generated by Django 4.2.1 on 2024-04-29 09:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Dog', '0005_alter_dog_managers_alter_dog_is_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dog',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
