# Generated by Django 4.2.1 on 2024-04-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dog', '0006_alter_dog_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dog',
            managers=[
            ],
        ),
    ]
